export const SET_USER_INFO = "SET_USER_INFO";
export const FETCH_BANNER_LIST = "FETCH_BANNER_LIST";
export const FETCH_MOVIE_LIST = "FETCH_MOVIE_LIST";
export const FETCH_COMMENT_LIST = "FETCH_COMMENT_LIST";
